# Generated by Django 3.1.8 on 2021-05-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('users', '0002_auto_20210503_0718'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salefile',
            name='attendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.storeattendant'),
        ),
        migrations.AddField(
            model_name='salefile',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.store'),
        ),
    ]
